### ISSUE TITLE
MASA.Auth Roadmap for 0.7.0

### ISSUE THREAD

**Issue by MayueCif** [masastack/MASA.Auth#343]
### Roadmap

This issue represents a list of major investments that our team will focus on in the 0.7.0 time frame. It doesn't include all the features and bug fixes we'll be working on in the meantime
这个Issue代表我们团队将在 0.7.0 内重点关注的列表。它不包括我们将在此期间进行的所有功能和错误修复。

Note that this is an aspirational list of what we hope to get to. Many of these items will require thorough investigation and design, which can result in changes to our plans. We will end up cutting some things and making changes as we go, but will try to keep this issue up to date to reflect on our progress and learnings.
请注意，这是一个我们希望达到的愿望清单。 其中许多项目需要彻底的调查和设计，这可能会导致我们的计划发生变化。我们最终可能会消减一些东西，并做出改变，但将努力保持这个Issue是最新的，以反映我们的进步和学习。  

The roadmap consists of the following features:
路线图包括以下特性

### User（用户）

**User（用户）**

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）
- [x] Advanced Search（高级查询）
- [x] User Permission（用户权限）

**ThirdPartyUser（第三方用户）**

- [x] List（列表）
- [x] Search（查询）
- [x] Advanced Search（高级查询）
- [x] Ldap Sync（域账号同步）

**Staff（员工）**

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）
- [x] Staff Sync（员工同步）
- [x] User Permission（用户权限）

### RolePermission（角色权限）

**Role（角色）**

- [x] List（列表）
- [x] Search（搜索）
- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）

**Permission（权限）**

- [x] List（列表）
- [x] Search（搜索）
- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）

### Team（团队）

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）

### SSO（单点登录）

**UserClaim（用户声明）**

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）
- [x] Quickly Create(快速创建)

**IdentityResource（身份资源）**

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）
- [x] Quickly Create(快速创建)

**ApiScope（Api范围）**

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）

**ApiResource（Api资源）**

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）

**Client（客户端）**

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）

**CustomLogin（自定义登录）**

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）

#### Organization（组织架构）

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）

#### ThirdPartyIdentityProvider（第三方平台）

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）

#### Position（职位）

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Search（查询）

#### OperationLog（操作日志）

- [x] List（列表）
- [x] Search（查询）
